# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_version = "1804.02"
  config.vm.define "web-lesson" do |box|
      box.vm.box = "centos/7"
      box.vm.hostname = "web-lesson"
      box.vm.provider "virtualbox" do |vb|
          vb.name = "web-lesson"
          vb.cpus = 1
          vb.memory = "2048"
      end
  end
  config.vm.network "forwarded_port", guest: 80, host: 3000
  config.vm.provision :shell, path: "script.sh"
end