# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :route1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.10.0.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "route-net"},
                   {ip: '10.30.0.2', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "route-net-3"},
                   {ip: '172.10.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "add-net1"},
                ]
  },
  
  :route2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.10.0.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "route-net"},
                   {ip: '10.20.0.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "route-net-2"},
                   {ip: '172.20.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "add-net2"},
                ]
  },
  :route3 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.20.0.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "route-net-2"},
                   {ip: '10.30.0.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "route-net-3"},
                   {ip: '172.30.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "add-net3"},
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
      end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbooks/playbook.yml"
  end
end
