# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME'] # Используем глобальную переменную $HOME

MACHINES = {
  :server => {
    :box_name => "centos/7",
    :box_version => "1804.02",
    :ip_addr => '192.168.11.100',
    :disks => {
        :sata1 => {
            :dfile => home + '/VirtualBox VMs/server_sata1.vdi',
            :size => 1024, # Megabytes
            :port => 1
        },
    }
  },
  :client => {
    :box_name => "centos/7",
    :box_version => "1804.02",
    :ip_addr => '192.168.11.101',
    :disks => {
        :sata1 => {
            :dfile => home + '/VirtualBox VMs/lvm/client_sata1.vdi',
            :size => 1024, # Megabytes
            :port => 1
        },
    }
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]

      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        needsController = false
        boxconfig[:disks].each do |dname, dconf|
          unless File.exist?(dconf[:dfile])
            vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
            needsController =  true
          end
        end
        if needsController == true
          vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          boxconfig[:disks].each do |dname, dconf|
              vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
          end
        end
      end
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
      config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbooks/playbook.yml"
      end
      if boxname.to_s == "server"
        box.vm.network :forwarded_port, guest: 9090, host: 9321
        box.vm.network :forwarded_port, guest: 3000, host: 9322
      end
    end
  end
end