# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_version = "1804.02"
  config.vm.define "bootlesson" do |box|
      box.vm.box = "centos/7"
      box.vm.hostname = "bootlesson"
      box.vm.provider "virtualbox" do |vb|
          vb.name = "bootlesson"
          vb.cpus = 1
          vb.memory = "256"
          vb.gui = true
      end
  end
end