# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box_version = "1804.02"
    config.vm.define "bashlesson" do |box|
        box.vm.box = "centos/7"
        box.vm.hostname = "bashlesson"
        box.vm.provider "virtualbox" do |vb|
            vb.name = "bashlesson"
            vb.cpus = 1
            vb.memory = "256"
        end
        box.vm.provision :shell, path: "./scripts/start.sh"
    end
  end