# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box_version = "1804.02"
    config.vm.define "auth-lesson" do |box|
        box.vm.box = "centos/7"
        box.vm.hostname = "auth-lesson"
        box.vm.provider "virtualbox" do |vb|
            vb.name = "auth-lesson"
            vb.cpus = 1
            vb.memory = "256"
        end
    end
    config.vm.provision :shell, path: "script.sh"
end