# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
        :os => "centos/7",
        :version => "1804.02",
        :ip_addr => "192.168.11.150",
        :memory => "256",
        :cpus => 1,
  }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:os]
            box.vm.box_version = boxconfig[:box_version]
            box.vm.host_name = boxname.to_s

            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider "virtualbox" do |vb|
                vb.name = boxname.to_s
                vb.cpus = boxconfig[:cpus]
                vb.memory = boxconfig[:memory]
            end
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "200"]
            end
        end
    end
end