# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
    :box_name => "centos/7",
    :net => [
                {ip: '192.168.1.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net"},
            ]
  },
  :slave => {
    :box_name => "centos/7",
    :net => [
                {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net"},
            ]
  },
  :barman => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.1.3', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net"},
            ]
}
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
      end

      config.vm.provider "virtualbox" do |v|
        v.memory = 3048
        v.cpus = 2
      end

      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end