# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
:server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.10.10', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "global-net"},
                   {ip: '172.168.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "local-net1"},
                ]
  },
:client => {

        :box_name => "centos/7",
        :net => [
                  {ip: '192.168.10.20', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "global-net"},
                  {ip: '172.168.20.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "local-net2"},                ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder "./", "/vagrant"
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 512
          v.cpus = 1
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

        case boxname.to_s
        when "server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            setenforce 0
            echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            yum install -y epel-release
            yum install -y openvpn iperf3 
            cp -r -n /vagrant/files/server/. /etc/openvpn/
            systemctl start openvpn@server
            systemctl enable openvpn@server
            SHELL
        when "client"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            setenforce 0
            echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            yum install -y epel-release
            yum install -y openvpn iperf3
            cp -r -n /vagrant/files/client/. /etc/openvpn/
            systemctl start openvpn@client
            systemctl enable openvpn@client
            SHELL
        end
      end

  end

end




# -*- mode: ruby -*-
# vim: set ft=ruby :

# MACHINES = {
#   :server => {
#         :box_name => "centos/7",
#         :net => [
#                    {ip: "192.168.0.1", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ovpn-net"},
#                 ]
#   },
  
#   :client => {
#         :box_name => "centos/7",
#         :net => [
#                    {ip: "192.168.0.2", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "ovpn-net"},
#                 ]
#   },

# }

# Vagrant.configure("2") do |config|

#   MACHINES.each do |boxname, boxconfig|
      
#     config.vm.define boxname do |box|

#         box.vm.box = boxconfig[:box_name]
#         box.vm.host_name = boxname.to_s

#         config.vm.provider "virtualbox" do |v|
#           v.memory = 256
#         end

#         boxconfig[:net].each do |ipconf|
#           box.vm.network "private_network", ipconf
#         end
              
#         box.vm.provision "shell", inline: <<-SHELL
#           mkdir -p ~root/.ssh
#                 cp ~vagrant/.ssh/auth* ~root/.ssh
#           timedatectl set-timezone Europe/Moscow
#         SHELL
        
#         case boxname.to_s
#           when "server"
#             box.vm.provision "shell", run: "always", inline: <<-SHELL
#               setenforce 0
#               echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
#               sysctl -p /etc/sysctl.conf
#               yum install epel-release -y
#               yum install openvpn traceroute -y
#               cp -r -n /vagrant/files/server/. /etc/openvpn/
#               systemctl enable openvpn@server.service
#               systemctl start openvpn@server.service
#               SHELL
#           when "client"
#             box.vm.provision "shell", run: "always", inline: <<-SHELL
#               setenforce 0
#               echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
#               sysctl -p /etc/sysctl.conf
#               yum install epel-release -y
#               yum install openvpn -y
#               cp -r -n /vagrant/files/client/. /etc/openvpn/
#               systemctl enable openvpn@client.service
#               systemctl start openvpn@client.service
#               SHELL
#           end
#        end
#    end
# end
